zrei/cs4350

- Assets/Prefabs/Battle/BattleManager.prefab
- Assets/Scripts/Battle/BattleManager.cs
- Assets/Scripts/Battle/BattleSO.cs
- Assets/Scripts/Battle/DamageCalc.cs
- Assets/Scripts/Battle/DamageCalc.cs.meta
- Assets/Scripts/Battle/Grid/GridLogic.cs
- Assets/Scripts/Battle/Map/MapLogic.cs
- Assets/Scripts/Battle/Turns/EnemyTurnManager.cs
- Assets/Scripts/Battle/Turns/PlayerTurnManager.cs
- Assets/Scripts/Battle/Turns/TurnManager.cs
- Assets/Scripts/Battle/Units/Unit.cs
- Assets/TestData/TestBattleSO.asset
> Turn order based on speed

- Assets/Scenes/TestMapScene.unity
- Assets/Scripts/Battle/BattleManager.cs
- Assets/Scripts/Battle/Grid/GridLogic.cs
- Assets/Scripts/Battle/TurnManagement/PlayerTurnManager.cs
- Assets/Scripts/Battle/TurnQueue.cs
- Assets/Scripts/Battle/Units/StatusManager.cs
- Assets/Scripts/Battle/Units/Unit.cs
> Status manager

- Assets/Scenes/TestMapScene.unity
- Assets/Scripts/Base/GlobalEvents.cs
- Assets/Scripts/Battle/BattleManager.cs
- Assets/Scripts/Battle/PlayerUnitSetup.cs
- Assets/Scripts/Battle/TurnManagement/EnemyTurnManager.cs
- Assets/Scripts/Battle/TurnManagement/PlayerTurnManager.cs
- Assets/Scripts/Battle/TurnQueue.cs
- Assets/Scripts/Battle/Units/StatusManager.cs
- Assets/Scripts/UI.meta
- Assets/Scripts/UI/UI_BattleResult.cs
- Assets/Scripts/UI/UI_BattleResult.cs.meta
- Assets/Scripts/UI/UI_PlayerInstructions.cs
- Assets/Scripts/UI/UI_PlayerInstructions.cs.meta
- Assets/Scripts/UI/UI_TurnOrder.cs
- Assets/Scripts/UI/UI_TurnOrder.cs.meta
Mostly for playtesting purposes
> Add preliminary UI

- Assets/Scenes/TestMapScene.unity
- Assets/Scripts/Base/GlobalSettings.cs
- Assets/Scripts/Base/ObjectPooler.cs
- Assets/Scripts/Battle/Grid/Pathfinder.cs
> Remove occupied squares as pass-through positions

- Assets/Scripts/Battle/Attacks/AttackAnimationManager.cs
- Assets/Scripts/Battle/Attacks/ICanAttack.cs
- Assets/Scripts/Battle/BattleManager.cs
- Assets/Scripts/Battle/DamageCalc.cs
- Assets/Scripts/Battle/Grid/GridLogic.cs
- Assets/Scripts/Battle/Units/Unit.cs
- Assets/Scripts/Persistent Data/Classes/Weapons/Active Skills/ActiveSkillEffects.meta
- Assets/Scripts/Persistent Data/Classes/Weapons/Active Skills/ActiveSkillEffects/ActiveSkillEffectSO.cs
- Assets/Scripts/Persistent Data/Classes/Weapons/Active Skills/ActiveSkillEffects/ActiveSkillEffectSO.cs.meta
- Assets/Scripts/Persistent Data/Classes/Weapons/Active Skills/ActiveSkillEffects/DealDamageEffectSO.cs
- Assets/Scripts/Persistent Data/Classes/Weapons/Active Skills/ActiveSkillEffects/DealDamageEffectSO.cs.meta
- Assets/Scripts/Persistent Data/Classes/Weapons/Active Skills/ActiveSkillEffects/InflictStatusEffectsSO.cs
- Assets/Scripts/Persistent Data/Classes/Weapons/Active Skills/ActiveSkillEffects/InflictStatusEffectsSO.cs.meta
- Assets/Scripts/Persistent Data/Classes/Weapons/Active Skills/ActiveSkillEffects/InflictTokensSO.cs
- Assets/Scripts/Persistent Data/Classes/Weapons/Active Skills/ActiveSkillEffects/InflictTokensSO.cs.meta
- Assets/Scripts/Persistent Data/Classes/Weapons/Active Skills/ActiveSkillSO.cs
- Assets/Scripts/Persistent Data/Classes/Weapons/WeaponSO.cs
- Assets/TestData/BigSwordSO.asset
- Assets/TestData/MagicAttack.asset
- Assets/TestData/MagicTokens.asset
- Assets/TestData/PhysicalNoStatus.asset
- Assets/TestData/PhysicalStatus.asset
- Assets/TestData/ShortSwordSO.asset
- Assets/TestData/StaffSO.asset
- Separate heal and damage modifiers
- Convert anims to weapon + skill
- Add a delay to the beginning of the next turn
(Includes the remnants of my refactoring efforts lmao)
> Convert anims to weapon + skill

- Assets/Prefabs/Cameras.prefab
- Assets/Scenes/TestMapScene.scenetemplate
- Assets/Scenes/TestMapScene_WithBattle.unity
- Assets/Skybox.meta
- Assets/Skybox/SkyboxMat.mat
- Assets/Skybox/SkyboxMat.mat.meta
Add a simple skybox to the main camera (is currently a flat colour with no texture)
> Add skybox

- Assets/Models/Characters/ArmsMask.mask
- Assets/Models/Characters/BaseElfFemale.fbx.meta
- Assets/Models/Characters/BaseElfMale.fbx.meta
- Assets/Models/Characters/BaseHumanFemale.fbx.meta
- Assets/Models/Characters/BaseHumanMale.fbx.meta
- Assets/Prefabs/RaceModels/ElfFemale.prefab
- Assets/Prefabs/RaceModels/ElfMale.prefab
- Assets/Prefabs/RaceModels/HumanFemale.prefab
- Assets/Prefabs/RaceModels/HumanMale.prefab
Previously models uses the root bone of hips instead which does not allow for humanoid avatar.
So I added a new root bone for all models and changed the avatar to use humanoid instead.
This change allowed for the same avatar mask to be used for all characters.
> Changes to models

- Assets/Scripts/Base/GlobalEvents.cs
- Assets/Scripts/Base/UI/HUD/ActionMenu.cs
- Assets/Scripts/Base/UI/HUD/CondensedUnitDisplay.cs
- Assets/Scripts/Base/UI/HUD/CurrentUnitMarker.cs
- Assets/Scripts/Base/UI/HUD/EnemyActionForecastDisplay.cs
- Assets/Scripts/Base/UI/HUD/TurnDisplay.cs
- Assets/Scripts/Base/UI/HUD/UI_BattleResult.cs
- Assets/Scripts/Base/UI/HUD/UI_PlayerInstructions.cs
- Assets/Scripts/Base/UI/HUD/UI_TurnOrder.cs
- Assets/Scripts/Base/UI/HUD/UnitDisplay.cs
- Assets/Scripts/Battle/BattleManager.cs
- Assets/Scripts/Battle/TurnQueue.cs
- Assets/Scripts/Level/Nodes/BattleNode.cs
Pass turn count back to level scene through the battle end event
> Pass turn count back to level scene

- Assets/Scripts/Battle/Grid/GridLogic.cs
- Assets/Scripts/Persistent Data/Active Skills/ActiveSkillSO.cs
- Assets/TestData/SummonSKillAction.asset
- Assets/TestData/SummonSKillAction.asset.meta
- Assets/TestData/TestSummonSkill.asset
- Assets/TestData/TestSummonSkill.asset.meta
- Assets/TestData/TestSummonerActionSet.asset
- Assets/TestData/TestSummonerActionSet.asset.meta
- Assets/TestData/TestSummonerCjharacter.asset
- Assets/TestData/TestSummonerCjharacter.asset.meta
- Assets/TestData/TestSummonerClass.asset
- Assets/TestData/TestSummonerClass.asset.meta
* Add summon skill (summons at grid logic level)
TODO:
* Bug with caching of decisions since it's done at the SO level, and the introduction of a new unit with the same class will result in a check of the same actions that clears cache for the upcoming unit and can result in empty lists
> Implement summon skill

- Assets/Persistent Data/ClassSOs/Player/Archer/Archer.asset
- Assets/Persistent Data/ClassSOs/Player/Archer/BowShot.asset
- Assets/Persistent Data/ClassSOs/Player/Archer/TacticalRetreat.asset
- Assets/Scripts/Battle/BattleManager.cs
- Assets/Scripts/Battle/Grid/GridLogic.cs
- Assets/Scripts/Battle/Inflictables/Tokens/Definition/TokenEnums.cs
- Assets/Scripts/Battle/Inflictables/Tokens/LifestealTokenTierSO.cs
- Assets/Scripts/Battle/Inflictables/Tokens/LifestealTokenTierSO.cs.meta
- Assets/Scripts/Battle/Inflictables/Tokens/ReflectTokenTierSO.cs
- Assets/Scripts/Battle/Inflictables/Tokens/ReflectTokenTierSO.cs.meta
- Assets/Scripts/Battle/Inflictables/Tokens/TokenStack.cs
- Assets/Scripts/Battle/Map/MapLogic.cs
- Assets/Scripts/Battle/Units/StatusManager.cs
- Assets/Scripts/Battle/Units/Unit.cs
- Assets/TestData/LifestealTokenTierSO.asset
- Assets/TestData/LifestealTokenTierSO.asset.meta
- Assets/TestData/Lifesteal_Tier1.asset
- Assets/TestData/Lifesteal_Tier1.asset.meta
- Assets/TestData/ReflectTier1.asset
- Assets/TestData/ReflectTier1.asset.meta
- Assets/TestData/ReflectTokenTier.asset
- Assets/TestData/ReflectTokenTier.asset.meta
* Implement lifesteal and reflect token
TODO:
* Refactor some of the token getters and streamline them
> [WIP] Reflect and lifesteal

- Assets/Persistent Data/CharacterSOs/Aether.asset
- Assets/Persistent Data/CharacterSOs/Bana.asset
- Assets/Persistent Data/CharacterSOs/Gordon.asset
- Assets/Scripts/Base/UI/HUD/EnemyActionForecastDisplay.cs
- Assets/Scripts/Battle/TurnManagement/PlayerTurnManager.cs
- Assets/Scripts/Battle/Units/EnemyAI/Actions/EnemyActionSO.cs
- Assets/Scripts/Battle/Units/EnemyAI/Actions/EnemyActiveSkillActionSO.cs
- Assets/Scripts/Battle/Units/EnemyAI/Actions/EnemyMoveActionSO.cs
- Assets/Scripts/Battle/Units/EnemyAI/Actions/EnemyPassActionSO.cs
- Assets/Scripts/Battle/Units/EnemyUnit.cs
- Assets/TestData/TestEasyBattleSO.asset
- Move calculations and caching to a runtime wrapper instance
> Move enemy action caching to a wrapper class

- Assets/Prefabs/GameManagers.prefab
- Assets/Scenes/TestLevelScene.unity
- Assets/Scripts/Base/GlobalEvents.cs
- Assets/Scripts/Battle/StatDefinitions.cs
- Assets/Scripts/Dialogue/Dialogue.cs
- Assets/Scripts/Dialogue/DialogueDisplay.cs
- Assets/Scripts/Inventory/InventoryManager.cs
- Assets/Scripts/Level/LevelManager.cs
- Assets/Scripts/Morality/MoralityManager.cs
- Assets/Scripts/Narrative.meta
- Assets/Scripts/Narrative/FlagManager.cs
- Assets/Scripts/Narrative/FlagManager.cs.meta
- Assets/Scripts/Persistent Data/CharacterDataManager.cs
- Assets/Scripts/Persistent Data/SaveManager.cs
* Add a flag manager (differentiate between session and persistent flags)
* Change persistent data managers to read from starting data if no save data exists
* Add morality changes to dialogue options
> [WIP] Narative + Save

- Assets/Prefabs/UI/HUD/ActionMenu/ActionButton.prefab
- Assets/Prefabs/UI/HUD/ActionMenu/ActionMenu.prefab
- Assets/Prefabs/UI/HUD/Controls.prefab
- Assets/Scripts/Base/Input/DefaultInputActions.inputactions
- Assets/Scripts/Base/Input/InputManager.cs
- Assets/Scripts/Base/UI/HUD/ActionButton.cs
- Assets/Scripts/Base/UI/HUD/ActionMenu.cs
- Assets/Scripts/Battle/TurnManagement/PlayerTurnManager.cs
- Assets/Scripts/Battle/Units/Unit.cs
- Fix skill page scrolling
- Implement action cancelling and movement undo
> Improve action menu

- Assets/Scripts/Narrative/FlagManager.cs
- Assets/Scripts/Persistent Data/CharacterDataManager.cs
- Assets/Scripts/Persistent Data/Levelling/LevellingManager.cs
* Character data manager checks for new class unlocks whenever game state changes
> Hook character data manager up to events

- Assets/Scenes/TestLevelScene.unity
- Assets/Scripts/Persistent Data/Classes/PathGroupSO.cs
* Fix index bug when checking for class unlocks
* Add unlocked classes into test data in level manager (temp fix until data is passed from the actual manager)
> Fix index exception for class unlock checking

- Assets/Persistent Data/Levels/Level 1/Level1SO.asset
- Assets/Prefabs/UI/Screens/LevelResultScreen/LevelResultScreen.prefab
- Assets/Scripts/Base/GlobalEvents.cs
- Assets/Scripts/Base/UI/Screens/LevelResultScreen.cs
- Assets/Scripts/Level/LevelManager.cs
- Assets/Scripts/Level/LevelSO.cs
- Assets/Scripts/Level/LevelTokenManager.cs
- Assets/Scripts/Persistent Data/CharacterDataManager.cs
Add level rewards to LevelSOs
Level rewards include adding new characters to roster and weapons
> Add level rewards

- Assets/Prefabs/Cameras.prefab
- Assets/Prefabs/UI/HUD/CharacterSelect.meta
- Assets/Prefabs/UI/HUD/CharacterSelect/PartySelectScreen.prefab
- Assets/Prefabs/UI/HUD/CharacterSelect/PartySelectScreen.prefab.meta
- Assets/Prefabs/UI/HUD/CharacterSelect/PartySelectionButton.prefab
- Assets/Prefabs/UI/HUD/CharacterSelect/PartySelectionButton.prefab.meta
- Assets/Scripts/Base/GlobalEvents.cs
- Assets/Scripts/Base/UI/HUD/LevelPreviewPanel.cs
- Assets/Scripts/Base/UI/HUD/NamedObjectButton.cs
- Assets/Scripts/Base/UI/HUD/PartySelectionSlotButton.cs
- Assets/Scripts/Base/UI/HUD/PartySelectionSlotButton.cs.meta
- Assets/Scripts/Base/UI/Screens/PartySelectScreen.cs
- Assets/Scripts/Base/UI/Screens/PartySelectScreen.cs.meta
- Assets/Scripts/Base/UI/UIScreenManager.cs
- Assets/Scripts/Level/LevelSO.cs
- Assets/Scripts/Persistent Data/CharacterDataManager.cs
- Assets/Scripts/WorldMap/WorldMapManager.cs
* Add party select screen (opens after pressing start level)
* Lord character is locked into first slot
* Pull lord data for world map token from character data manager
TODO:
* Update tokens with character management
* Add character management to world map
* Add pre+post cutscenes to world map
> Level party select

- Assets/Prefabs/UI/HUD/Controls.prefab
- Assets/Prefabs/UI/HUD/ControlsDisplay.prefab
- Assets/Prefabs/UI/HUD/WorldMapControls.prefab
- Assets/Prefabs/UI/HUD/WorldMapControls.prefab.meta
- Assets/Scripts/Base/GlobalEvents.cs
- Assets/Scripts/Base/UI/HUD/ControlsDisplay.cs
- Assets/Scripts/Base/UI/Screens/CharacterManagementScreen.cs
- Assets/Scripts/Inventory/InventoryManager.cs
- Assets/Scripts/Level/LevelManager.cs
- Assets/Scripts/Persistent Data/CharacterDataManager.cs
- Assets/Scripts/WorldMap/WorldMapManager.cs
* Add a bool to the party management to dictate if saving is done upon closing the menu
> Add world map controls and party management to world map

- Assets/Models/Materials/Environment/Fog.mat
- Assets/Scenes/WorldMapScene.unity
- Assets/Scripts/FogFader.cs
- Assets/Scripts/FogFader.cs.meta
- Assets/Scripts/WorldMap/WorldMapManager.cs
* Add fog enabling/disabling depending on progression
[WIP] actually fade the fog
> [WIP] Fog transition

- Assets/Prefabs/UI/HUD/SaveDisplay/SaveDisplay.prefab
- Assets/Scenes/WorldMapScene.unity
> [MergeAfter #145] Fix save display positioning

- Assets/Scripts/Sound/SoundManager.cs
* Fix this obscure sound bug that happens if you tab out of the editor the instant you press play (not sure if it'll affect actual build but eh)
> Fix main menu sound bug

- Assets/Persistent Data/ClassSOs/Player/Mage/Mage.asset
- Assets/Persistent Data/ClassSOs/Player/Paladin/Paladin.asset
- Assets/Persistent Data/ClassSOs/Player/Priest/PriestSO.asset
- Assets/Scripts/Battle/BattleManager.cs
- Assets/Scripts/Battle/Grid/GridLogic.cs
- Assets/Scripts/Battle/Map/MapLogic.cs
- Assets/Scripts/Battle/PlayerUnitSetup.cs
- Assets/Scripts/Persistent Data/Classes/PlayerClassSO.cs
* Also fix the preview tile visual
> Add class placement

- Assets/Prefabs/UI/Screens/PauseScreen/PauseScreen.prefab
- Assets/Scripts/Base/UI/Screens/CharacterManagementScreen/CharacterManagementScreen.cs
- Assets/Scripts/Base/UI/Screens/PartySelectScreen.cs
- Assets/Scripts/Base/UI/Screens/PauseScreen.cs
Save before starting level and when quitting to main menu from the world map.
> Change when saving occurs

- Assets/Persistent Data/Inflictables/Tokens/AttackBoost/AttackBoost.asset
- Assets/Persistent Data/Inflictables/Tokens/AttackDown/AttackDown.asset
- Assets/Persistent Data/Inflictables/Tokens/Crit/Crit.asset
- Assets/Scripts/Battle/Inflictables/StatusEffects/StatusEffect.cs
* Add required consumption types to attack ups and crit
* Fix status effect stacking
> Heal mana tokens

- Assets/Prefabs/Cutscenes/Tokens/NPCCutsceneToken.prefab
- Assets/Prefabs/Cutscenes/Tokens/NPCCutsceneToken.prefab.meta
- Assets/Scripts/Battle/Units/ArmorVisual.cs
- Assets/Scripts/Cutscene/CutsceneToken.cs
- Assets/Scripts/Cutscene/EnemyCutsceneToken.cs
- Assets/Scripts/Cutscene/NPCCutsceneToken.cs
- Assets/Scripts/Cutscene/NPCCutsceneToken.cs.meta
- Assets/Scripts/Cutscene/PlayerCharacterCutsceneToken.cs
* Create NPC cutscene tokens --> can directly specify the armor, race, gender, colors etc.
* Give option to spawn cutscene tokens with and without weapons --> will have idle pose if spawned without weapons
> [MergeAfter gold] Add npc tokens

- Assets/Persistent Data/Inflictables/Tokens/AttackDown/AttackDown.asset
- Assets/Persistent Data/Inflictables/Tokens/DefenceDown/DefenceDown.asset
- Assets/Persistent Data/Inflictables/Tokens/Hunger/Hunger.asset
- Assets/Persistent Data/Inflictables/Tokens/SpeedDown/SpeedDown.asset
- Assets/Persistent Data/Inflictables/Tokens/Stun/Stun.asset
- Assets/Persistent Data/Inflictables/Tokens/Taunt/Taunt.asset
- Assets/Scripts/Battle/Inflictables/Tokens/Definition/TokenTierSO.cs
- Assets/Scripts/Battle/Inflictables/Tokens/TokenStack.cs
- Assets/Scripts/Battle/Units/StatusManager.cs
- Assets/Scripts/Battle/Units/Unit.cs
- Assets/Scripts/Persistent Data/Active Skills/ActiveSkillSO.cs
- Assets/Scripts/Persistent Data/Active Skills/SkillEnums.cs
* Add cleanse skill type
* Can specify if we are cleansing status effects, buff or debuff tokens
* Add buff boolean to token tiers
> [MergeAfter Gold] Add cleanse skill type

- Assets/Scenes/WorldMapScene.unity
- Assets/Scripts/Base/BaseEdge.cs
- Assets/Scripts/Base/BaseEdge.cs.meta
- Assets/Scripts/Level/Edges/EdgeInternal.cs
- Assets/Scripts/WorldMap/Paths/WorldMapEdge.cs
* Will be drawn when edge is selected
> Add node gizmos to indicate start and end of edge

- Assets/Prefabs/UI/Screens/CharacterManagementScreen/CharacterManagementScreen.prefab
- Assets/Prefabs/UI/Screens/PartySelectScreen/PartySelectScreen.prefab
- Assets/Prefabs/UI/Screens/TutorialButton.prefab
- Assets/Prefabs/UI/Screens/TutorialButton.prefab.meta
- Assets/Scripts/Base/UI/Screens/CharacterManagementScreen/CharacterManagementScreen.cs
- Assets/Scripts/Base/UI/Screens/PartySelectScreen/PartySelectScreen.cs
* Create tutorial button prefab
* Add tutorial buttons to party select + character management
> Screen tutorial buttons

- Assets/Scripts/Battle/Grid/GridLogic.cs
- Assets/Scripts/Battle/Grid/Pathfinder.cs
- Assets/Scripts/Battle/Units/Unit.cs
- Assets/Scripts/Persistent Data/Classes/ClassSO.cs
* Implement diagonal movement by creating enum that defines movement type and using that to fill out the queue when pathfinding
* This is set at a class level
* Tested the movement anim it looks fine
> Diagonal movement

- Assets/Persistent Data/TutorialSO.meta
- Assets/Persistent Data/TutorialSO/CharacterManagementTutorial.asset
- Assets/Persistent Data/TutorialSO/CharacterManagementTutorial.asset.meta
- Assets/Persistent Data/TutorialSO/PartySelectTutorial.asset
- Assets/Persistent Data/TutorialSO/PartySelectTutorial.asset.meta
- Assets/Persistent Data/TutorialSO/WorldMapTutorial.asset
- Assets/Persistent Data/TutorialSO/WorldMapTutorial.asset.meta
- Assets/Prefabs/Managers/WorldMapManager.prefab
- Assets/Prefabs/UI/Screens/CharacterManagementScreen/CharacterManagementScreen.prefab
- Assets/Prefabs/UI/Screens/PartySelectScreen/PartySelectScreen.prefab
- Assets/Scripts/Base/UI/Screens/CharacterManagementScreen/CharacterManagementScreen.cs
- Assets/Scripts/Base/UI/Screens/PartySelectScreen/PartySelectScreen.cs
- Assets/Scripts/Battle/BattleManager.cs
- Assets/Scripts/Battle/BattleSO.cs
- Assets/Scripts/Level/Nodes/NodeInternal.cs
- Assets/Scripts/Tutorial.meta
- Assets/Scripts/Tutorial/TutorialSO.cs
- Assets/Scripts/Tutorial/TutorialSO.cs.meta
- Assets/Scripts/WorldMap/WorldMapManager.cs
* Move tutorial page UI lists to tutorial SOs so it can be reused in any tutorial compilations
> Add tutorial SOs

- Assets/Persistent Data/Levels/Level 3/Level3SO.asset
- Assets/Persistent Data/Levels/Level 3/NodeData/Lvl3BossNodeDataSO.asset
- Assets/Persistent Data/Levels/Level 3/NodeData/Lvl3EliteEnemy1NodeDataSO.asset
- Assets/Persistent Data/Levels/Level 3/NodeData/Lvl3StartNodeDataSO.asset
- Assets/Persistent Data/Levels/Level 4/Dialogue/Lvl4DialogueA.prefab
- Assets/Persistent Data/Levels/Level 4/Dialogue/Lvl4DialogueB.prefab
- Assets/Persistent Data/Levels/Level 4/Dialogue/Lvl4DialogueC.prefab
- Assets/Persistent Data/Levels/Level 4/Dialogue/Lvl4PostBossDialogue.prefab
- Assets/Persistent Data/Levels/Level 4/Dialogue/Lvl4PostBossDialogue.prefab.meta
- Assets/Persistent Data/Levels/Level 4/NodeData/Lvl4BossNodeDataSO.asset
- Assets/Prefabs/Dialogues.meta
- Assets/Prefabs/Dialogues/Lord.prefab
- Assets/Prefabs/Dialogues/Lord.prefab.meta
- Assets/Prefabs/Dialogues/Mage.prefab
- Assets/Prefabs/Dialogues/Mage.prefab.meta
- Assets/Prefabs/Dialogues/Paladin.prefab
- Assets/Prefabs/Dialogues/Paladin.prefab.meta
- Assets/Scenes/Level3Scene.unity
- Assets/Scenes/Level4Scene.unity
- Assets/Scripts/Level/LevelManager.cs
Tidy up level 3 and 4 node arrangements
> Setup level 4 dialogues

- Assets/Scenes/TestScenes/TestBattleAdditiveScene.unity
- Assets/Scenes/TestScenes/TestBattleAdditiveScene.unity.meta
- Assets/Scripts/Battle/BattleManager.cs
- Assets/Scripts/Battle/Test/TestBattleInitialiser.cs
- Assets/Scripts/Helper/Tools/SceneLoad/SceneLoadTool.cs
* For all your testing needs ~
* You can load the test battle additive scene from the scene load tool to set the test settings
* Then load the game in whatever biome you want from the scene load tool
> Add test battle additive scene
